endpoints:
  prometheus:
    sensitive: false

micronaut:
  router:
    static-resources:
        swagger:
          paths: classpath:META-INF/swagger
          mapping: /swagger/**
        swagger-ui:
          paths: classpath:META-INF/swagger/views/swagger-ui
          mapping: /swagger-ui/**
  metrics:
    enabled: true
    export:
      prometheus:
        enabled: true
        step: PT1M
        descriptions: true
  application:
    name: mnms
  executors:
    consumer:
      type: FIXED
    
kafka:
  bootstrap:
    servers: localhost:29092
  # security:
  #   protocol: ssl
  # streams:
  #     default:
  #       processing.guarantee: "exactly_once"
  #       auto.offset.reset: "earliest"

datasources:
  default:
    url: jdbc:postgresql://localhost:5432/postgres
    driverClassName: org.postgresql.Driver
    username: postgres
    password: password
    schema-generate: CREATE_DROP
    dialect: POSTGRES

jpa:
  default:
    entity-scan:
        packages: 'mnms'

rabbitmq:
    uri: amqp://localhost:5672
    username: guest
    password: guest