endpoints:
  prometheus:
    sensitive: false

micronaut:
  metrics:
    enabled: true
    export:
      prometheus:
        enabled: true
        step: PT1M
        descriptions: true
  application:
    name: mnms
    
kafka:
  bootstrap:
    servers: localhost:29092
  streams:
      default:
        processing.guarantee: "exactly_once"
        auto.offset.reset: "earliest"

datasources:
  default:
    url: jdbc:postgresql://localhost:5432/postgres
    driverClassName: org.postgresql.Driver
    username: postgres
    password: password
    schema-generate: CREATE_DROP
    dialect: POSTGRES

jpa:
  default:
    entity-scan:
        packages: 'mnms'
        